[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css','scss','sass']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''
on_ft = ['json']

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
hook_add = '''
  let g:latex_to_unicode_keymap = 1
  noremap <expr> <F7> LaTeXtoUnicode#Toggle()
  noremap! <expr> <F7> LaTeXtoUnicode#Toggle()
'''
on_ft = ['julia']

[[plugins]]
repo = 'yschu7/FIGlet.vim'
on_cmd = ['FIGlet']

