[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
hook_add = '''
  let g:latex_to_unicode_keymap = 1
  noremap <expr> <F7> LaTeXtoUnicode#Toggle()
  noremap! <expr> <F7> LaTeXtoUnicode#Toggle()
'''
on_ft = ['julia']

[[plugins]]
repo = 'yschu7/FIGlet.vim'
on_cmd = ['FIGlet']

[[plugins]]
repo = 'tpope/vim-scriptease'
on_ft = ['vim']

[[plugins]]
repo = 'alaviss/nim.nvim'

[[plugins]]
repo = 'metakirby5/codi.vim'

[[plugins]]
repo = 'sbdchd/neoformat'

